name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Your site is already prebuilt in dist/, so no build step needed
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project elixiary
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
