name: Healthchecks

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:         # allow manual run from Actions tab

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check www and API
        shell: bash
        run: |
          set -euxo pipefail
          curl -fsS --max-time 15 https://www.elixiary.com/ -o /dev/null
          curl -fsS --max-time 15 "https://api.elixiary.com/v1/list?page=1&page_size=1" -o /dev/null

      - name: Write summary (always)
        if: always()
        run: |
          {
            echo "## Healthcheck summary"
            echo ""
            echo "- Site: https://www.elixiary.com/"
            echo "- API : https://api.elixiary.com/v1/list?page=1&page_size=1"
            echo "- Result: ${{ job.status }}"
            echo "- Time: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          } >> "$GITHUB_STEP_SUMMARY"
