name: Deploy Cloudflare Worker
on:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: worker
          command: deploy
        env:
          # This environment var will be uploaded as a Worker secret (first time)
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        # The action auto-syncs env vars listed under `env:` as secrets on first run
